import { Inria_Sans } from "next/font/google";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";

const inria_sans = Inria_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-inria-sans",
});

const josefin_sans = Josefin_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--font-josefin-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inria_sans.variable} ${josefin_sans.variable}`}>
        {children}
      </body>
    </html>
  );
}
